### ISSUE TITLE
Error: rate limit exceeded

### ISSUE THREAD

**Issue by EvaMart** [inab/opeb-enrichers#4]
I get the following error when running the repo-enricher. It happens after processing some repositories successfully. The execution of the program continues, but all attempts to process repositories raise the same error. 

```bash
* Processing MathLee ACCoNet
Kicked out https://api.github.com/repos/MathLee/ACCoNet: 403
Traceback (most recent call last):
    File "/opeb-enrichers/repoEnricher/repo_enricher/repo_matcher/abstract.py", line 117, in fetchJSON
        with self._opener(req) as response:
    File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
    File "/usr/lib/python3.10/urllib/request.py", line 525, in open
        response = meth(req, response)
    File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
        response = self.parent.error(
    File "/usr/lib/python3.10/urllib/request.py", line 563, in error
        return self._call_chain(*args)
    File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
        result = func(*args)
    File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
       raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
```
I checked the token I am using and it seems fine, it is not expired. 

Maybe the rate limits of the GitHub REST API have changed? 🤔

**Comment by EvaMart** [comment]
From GitHub [REST API documentation](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting) on resources limits:

"User access token requests are limited to 5,000 requests per hour and per authenticated user. All requests from OAuth apps authorized by a user or a personal access token owned by the user, and requests authenticated with any of the user's authentication credentials, share the same quota of 5,000 requests per hour for that user."
